// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* t19_promise_cases_memory; u32 t19_promise_cases_memory_pages = 1;

void t19_promise_cases__porf_init(void) {
  if (t19_promise_cases_memory) return;
  t19_promise_cases_memory = calloc(1, t19_promise_cases_memory_pages * 65536);

}



int t19_promise_cases_main() {
  t19_promise_cases__porf_init();


  return 0;
}