#include "dong_gpu_format.h"

int dong_image_format_is_gpu_compressed(DongImageFormat format) {
    return dong_image_format_is_compressed(format);
}

DongGPUTextureFormat dong_image_format_to_gpu_texture_format(DongImageFormat format) {
    switch (format) {
    case DONG_IMAGE_FORMAT_RGBA8: return DONG_GPU_TEXTURE_FORMAT_RGBA8_UNORM;
    case DONG_IMAGE_FORMAT_R8: return DONG_GPU_TEXTURE_FORMAT_R8_UNORM;
    case DONG_IMAGE_FORMAT_BC1: return DONG_GPU_TEXTURE_FORMAT_BC1_UNORM;
    case DONG_IMAGE_FORMAT_BC3: return DONG_GPU_TEXTURE_FORMAT_BC3_UNORM;
    case DONG_IMAGE_FORMAT_BC4: return DONG_GPU_TEXTURE_FORMAT_BC4_UNORM;
    case DONG_IMAGE_FORMAT_BC5: return DONG_GPU_TEXTURE_FORMAT_BC5_UNORM;
    case DONG_IMAGE_FORMAT_BC6H: return DONG_GPU_TEXTURE_FORMAT_BC6H_UNORM;
    case DONG_IMAGE_FORMAT_BC7: return DONG_GPU_TEXTURE_FORMAT_BC7_UNORM_SRGB;
    case DONG_IMAGE_FORMAT_ASTC_4x4: return DONG_GPU_TEXTURE_FORMAT_ASTC_4x4_UNORM_SRGB;
    case DONG_IMAGE_FORMAT_ASTC_5x5: return DONG_GPU_TEXTURE_FORMAT_ASTC_5x5_UNORM;
    case DONG_IMAGE_FORMAT_ASTC_6x6: return DONG_GPU_TEXTURE_FORMAT_ASTC_6x6_UNORM_SRGB;
    case DONG_IMAGE_FORMAT_ASTC_8x8: return DONG_GPU_TEXTURE_FORMAT_ASTC_8x8_UNORM;
    default: return DONG_GPU_TEXTURE_FORMAT_RGBA8_UNORM;
    }
}

DongImageFormat dong_gpu_texture_format_to_image_format(DongGPUTextureFormat format) {
    switch (format) {
    case DONG_GPU_TEXTURE_FORMAT_RGBA8_UNORM: return DONG_IMAGE_FORMAT_RGBA8;
    case DONG_GPU_TEXTURE_FORMAT_R8_UNORM: return DONG_IMAGE_FORMAT_R8;
    case DONG_GPU_TEXTURE_FORMAT_BC1_UNORM: return DONG_IMAGE_FORMAT_BC1;
    case DONG_GPU_TEXTURE_FORMAT_BC3_UNORM: return DONG_IMAGE_FORMAT_BC3;
    case DONG_GPU_TEXTURE_FORMAT_BC4_UNORM: return DONG_IMAGE_FORMAT_BC4;
    case DONG_GPU_TEXTURE_FORMAT_BC5_UNORM: return DONG_IMAGE_FORMAT_BC5;
    case DONG_GPU_TEXTURE_FORMAT_BC6H_UNORM: return DONG_IMAGE_FORMAT_BC6H;
    case DONG_GPU_TEXTURE_FORMAT_BC7_UNORM:
    case DONG_GPU_TEXTURE_FORMAT_BC7_UNORM_SRGB: return DONG_IMAGE_FORMAT_BC7;
    case DONG_GPU_TEXTURE_FORMAT_ASTC_4x4_UNORM:
    case DONG_GPU_TEXTURE_FORMAT_ASTC_4x4_UNORM_SRGB: return DONG_IMAGE_FORMAT_ASTC_4x4;
    case DONG_GPU_TEXTURE_FORMAT_ASTC_5x5_UNORM: return DONG_IMAGE_FORMAT_ASTC_5x5;
    case DONG_GPU_TEXTURE_FORMAT_ASTC_6x6_UNORM:
    case DONG_GPU_TEXTURE_FORMAT_ASTC_6x6_UNORM_SRGB: return DONG_IMAGE_FORMAT_ASTC_6x6;
    case DONG_GPU_TEXTURE_FORMAT_ASTC_8x8_UNORM: return DONG_IMAGE_FORMAT_ASTC_8x8;
    default: return DONG_IMAGE_FORMAT_RGBA8;
    }
}
