// generated by porffor 
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* _memory; u32 _memoryPages = 1;

static f64 __porf_import_dong_add(f64 p0, f64 p1) {
  return p0 + p1;
}



int main() {
  _memory = calloc(1, _memoryPages * 65536);



  return 0;
}