// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* t15_memory; u32 t15_memory_pages = 1;

void t15__porf_init(void) {
  if (t15_memory) return;
  t15_memory = calloc(1, t15_memory_pages * 65536);

}

struct ReturnValue t15_onClick(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype);
struct ReturnValue t15_getCount(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype);
static i32 t15__Porffor_object_isObject(i32 arg, i32 argjjtype);
struct ReturnValue t15_echoArg(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype, f64 x, i32 xjjtype);

static f64 t15_count = 0;
static i32 t15_countjjtype = 0;

int t15_main() {
  t15__porf_init();

  t15_count = 0;
  t15_countjjtype = 1;

  return 0;
}

struct ReturnValue t15_onClick(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype) {
  i32 _get2;
  f64 _get1;
  f64 _get0;
  t15_count = t15_count + 1;
  t15_countjjtype = 1;
  _get0 = jjnewtarget;
  // if 
    if (((u32)(_get0)) != 0) {
      _get1 = jjthis;
      _get2 = jjthisjjtype;
      return (struct ReturnValue){ _get1, _get2 };
    }
  // end
  j0:;
  return (struct ReturnValue){ 0, 0 };
}

static i32 t15__Porffor_object_isObject(i32 arg, i32 argjjtype) {
  i32 _get4;
  i32 _get3;
  i32 _get2;
  i32 _get1;
  i32 _get0;
  i32 t = 0;

  _get0 = argjjtype;
  t = _get0;
  _get1 = arg;
  _get2 = t;
  _get3 = t;
  _get4 = t;
  return (((_get1 != 0) & (_get2 > 5)) & (_get3 != 67)) & (_get4 != 195);
}

struct ReturnValue t15_getCount(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype) {
  i32 _get6;
  f64 _get5;
  i32 _get4;
  f64 _get3;
  i32 _get2;
  f64 _get1;
  f64 _get0;
  f64 jjreturn = 0;
  i32 jjreturnjjtype = 0;

  jjreturn = t15_count;
  jjreturnjjtype = t15_countjjtype;
  _get0 = jjnewtarget;
  // if 
    if (((u32)(_get0)) != 0) {
      _get1 = jjreturn;
      _get2 = jjreturnjjtype;
      // if 
        if ((t15__Porffor_object_isObject((i32)(_get1), _get2)) == 0) {
          _get3 = jjthis;
          _get4 = jjthisjjtype;
          return (struct ReturnValue){ _get3, _get4 };
        }
      // end
      j2:;
    }
  // end
  j1:;
  _get5 = jjreturn;
  _get6 = jjreturnjjtype;
  return (struct ReturnValue){ _get5, _get6 };
}

struct ReturnValue t15_echoArg(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype, f64 x, i32 xjjtype) {
  i32 _get8;
  f64 _get7;
  i32 _get6;
  f64 _get5;
  i32 _get4;
  f64 _get3;
  f64 _get2;
  i32 _get1;
  f64 _get0;
  f64 jjreturn = 0;
  i32 jjreturnjjtype = 0;

  _get0 = x;
  jjreturn = _get0;
  _get1 = xjjtype;
  jjreturnjjtype = _get1;
  _get2 = jjnewtarget;
  // if 
    if (((u32)(_get2)) != 0) {
      _get3 = jjreturn;
      _get4 = jjreturnjjtype;
      // if 
        if ((t15__Porffor_object_isObject((i32)(_get3), _get4)) == 0) {
          _get5 = jjthis;
          _get6 = jjthisjjtype;
          return (struct ReturnValue){ _get5, _get6 };
        }
      // end
      j4:;
    }
  // end
  j3:;
  _get7 = jjreturn;
  _get8 = jjreturnjjtype;
  return (struct ReturnValue){ _get7, _get8 };
}

int t15_export_onClick(void) {
  t15__porf_init();
  (void)t15_onClick(0, 0, 0, 0);
  return 0;
}

int t15_export_getCount(void) {
  t15__porf_init();
  (void)t15_getCount(0, 0, 0, 0);
  return 0;
}

int t15_export_echoArg(f64 p0) {
  t15__porf_init();
  (void)t15_echoArg(0, 0, 0, 0, p0, 1);
  return 0;
}