// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* _memory; u32 _memoryPages = 1;

static f64 __Number_isNaN(f64 l0);

static f64 a = 0;
static i32 ajjtype = 0;
static f64 b = 0;
static i32 bjjtype = 0;
static f64 c = 0;
static i32 cjjtype = 0;
static f64 ok = 0;
static i32 okjjtype = 0;

static f64 __Number_isNaN(f64 l0) {
  f64 _get1;
  f64 _get0;
  _get0 = l0;
  _get1 = l0;
  return (f64)(_get0 != _get1);
}

int main() {
  i32 _get9;
  f64 _get8;
  i32 _get7;
  i32 _get6;
  f64 _get5;
  f64 _get4;
  i32 _get3;
  f64 _get2;
  f64 _get1;
  f64 _get0;
  _memory = calloc(1, _memoryPages * 65536);


  f64 logictmp = 0;
  i32 jjlast_type = 0;
  f64 jjlogicinner_tmp = 0;
  i32 jjtypeswitch_tmp1 = 0;

  a = __porf_nan;
  ajjtype = 1;
  b = __porf_infinity;
  bjjtype = 1;
  c = -__porf_infinity;
  cjjtype = 1;
  logictmp = __Number_isNaN(a);
  _get0 = logictmp;
  const f64 _tmp0 = _get0;
  // if f64
  f64 _r0;
    if ((_tmp0 < 0 ? -_tmp0 : _tmp0) > 0) {
      jjlast_type = 2;
      _r0 = (f64)(b > 1e+100);
    } else {
      _get1 = logictmp;
      jjlast_type = 2;
      _r0 = _get1;
    }
  // end
  j0:;
  logictmp = _r0;
  _get2 = logictmp;
  jjlogicinner_tmp = _get2;
  _get3 = jjlast_type;
  jjtypeswitch_tmp1 = _get3;
  _get4 = jjlogicinner_tmp;
  const f64 _tmp1 = _get4;
  // if f64
  f64 _r1;
    if ((_tmp1 < 0 ? -_tmp1 : _tmp1) > 0) {
      jjlast_type = 2;
      _r1 = (f64)(c < -1e+100);
    } else {
      _get5 = logictmp;
      _get6 = jjlast_type;
      jjlast_type = _get6;
      _r1 = _get5;
    }
  // end
  j1:;
  ok = _r1;
  _get7 = jjlast_type;
  okjjtype = _get7;
  jjlogicinner_tmp = ok;
  jjtypeswitch_tmp1 = okjjtype;
  _get8 = jjlogicinner_tmp;
  const f64 _tmp2 = _get8;
  // if f64
  f64 _r2;
    if ((_tmp2 < 0 ? -_tmp2 : _tmp2) > 0) {
      jjlast_type = 1;
      _r2 = 42;
    } else {
      jjlast_type = 1;
      _r2 = 0;
    }
  // end
  j2:;
  _get9 = jjlast_type;

  return 0;
}