// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* mod_b_memory; u32 mod_b_memory_pages = 1;

void mod_b__porf_init(void) {
  if (mod_b_memory) return;
  mod_b_memory = calloc(1, mod_b_memory_pages * 65536);

}



static f64 mod_b_y = 0;
static i32 mod_b_yjjtype = 0;

int mod_b_main() {
  mod_b__porf_init();

  mod_b_y = 2;
  mod_b_yjjtype = 1;

  return 0;
}