// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* _memory; u32 _memoryPages = 1;


__attribute__((import_module(""), import_name("c")))
extern f64 __porf_import_time();
static i32 i32_load(i32 align, i32 offset, i32 pointer) {
  return *((i32*)(_memory + offset + pointer));
}

static void i32_store(i32 align, i32 offset, i32 pointer, i32 value) {
  *((i32*)(_memory + offset + pointer)) = value;
}

static i32 i32_load8_u(i32 align, i32 offset, i32 pointer) {
  return *((u8*)(_memory + offset + pointer));
}

static void i32_store16(i32 align, i32 offset, i32 pointer, u16 value) {
  *((u16*)(_memory + offset + pointer)) = value;
}


__attribute__((import_module(""), import_name("b")))
extern void __porf_import_printChar(f64);

__attribute__((import_module(""), import_name("a")))
extern void __porf_import_print(f64);
static f64 __performance_now();
static struct ReturnValue __Porffor_strcat(i32 a, i32 ajjtype, i32 b, i32 bjjtype);
static i32 __Porffor_malloc(i32 l0);

static f64 a = 0;
static i32 ajjtype = 0;
static f64 b = 0;
static i32 bjjtype = 0;
static f64 c = 0;
static i32 cjjtype = 0;
static f64 d = 0;
static i32 djjtype = 0;
static f64 e = 0;
static i32 ejjtype = 0;
static f64 t = 0;
static i32 tjjtype = 0;
static f64 i = 0;
static i32 ijjtype = 0;
static f64 _ = 0;
static i32 _jjtype = 0;
static i32 jjporfjjcurrentPtr = 0;
static i32 jjporfjjcurrentPtrjjglbl_inited = 0;
static i32 jjporfjjendPtr = 0;
static i32 jjporfjjendPtrjjglbl_inited = 0;

static f64 __performance_now() {
  return __porf_import_time();
}

static i32 __Porffor_malloc(i32 l0) {
  i32 _get5;
  i32 _get4;
  i32 _get3;
  i32 _get2;
  i32 _get0;
  _get0 = l0;
  // if i32
  i32 _r5;
    if ((jjporfjjcurrentPtr + _get0) >= jjporfjjendPtr) {
      const u32 _oldPages1 = _memoryPages;
      _memoryPages += 16;
      _memory = realloc(_memory, _memoryPages * 65536);
      memset(_memory + _oldPages1 * 65536, 0, (_memoryPages - _oldPages1) * 65536);
      _get2 = l0;
      jjporfjjcurrentPtr = (_oldPages1 * 65536) + _get2;
      _get3 = l0;
      jjporfjjendPtr = (jjporfjjcurrentPtr + 1048576) - _get3;
      _get4 = l0;
      _r5 = jjporfjjcurrentPtr - _get4;
    } else {
      _get5 = l0;
      jjporfjjcurrentPtr = jjporfjjcurrentPtr + _get5;
      _r5 = jjporfjjcurrentPtr;
    }
  // end
  j5:;
  return _r5;
}

static struct ReturnValue __Porffor_strcat(i32 a, i32 ajjtype, i32 b, i32 bjjtype) {
  i32 _get65;
  i32 _get64;
  i32 _get63;
  i32 _get62;
  i32 _get61;
  i32 _get60;
  i32 _get59;
  i32 _get58;
  i32 _get57;
  i32 _get56;
  i32 _get55;
  i32 _get54;
  i32 _get53;
  i32 _get52;
  i32 _get51;
  i32 _get50;
  i32 _get49;
  i32 _get48;
  i32 _get47;
  i32 _get46;
  i32 _get45;
  i32 _get44;
  i32 _get43;
  i32 _get42;
  i32 _get41;
  i32 _get40;
  i32 _get39;
  i32 _get38;
  i32 _get37;
  i32 _get36;
  i32 _get35;
  i32 _get34;
  i32 _get33;
  i32 _get32;
  i32 _get31;
  i32 _get30;
  i32 _get29;
  i32 _get28;
  i32 _get27;
  i32 _get26;
  i32 _get25;
  i32 _get24;
  i32 _get23;
  i32 _get22;
  i32 _get21;
  i32 _get20;
  i32 _get19;
  i32 _get18;
  i32 _get17;
  i32 _get16;
  i32 _get15;
  i32 _get14;
  i32 _get13;
  i32 _get12;
  i32 _get11;
  i32 _get10;
  i32 _get9;
  i32 _get8;
  i32 _get7;
  i32 _get6;
  i32 _get5;
  i32 _get4;
  i32 _get3;
  i32 _get2;
  i32 _get1;
  i32 _get0;
  i32 al = 0;
  i32 bl = 0;
  i32 out = 0;
  i32 i = 0;
  i32 ptr = 0;

  _get0 = a;
  al = i32_load(0, 0, _get0);
  _get1 = b;
  bl = i32_load(0, 0, _get1);
  _get2 = ajjtype;
  // if 
    if (_get2 == 195) {
      _get3 = bjjtype;
      // if 
        if (_get3 == 195) {
          _get4 = al;
          _get5 = bl;
          out = __Porffor_malloc((6 + _get4) + _get5);
          _get6 = out;
          _get7 = al;
          _get8 = bl;
          i32_store(0, 0, _get6, _get7 + _get8);
          _get9 = out;
          _get10 = a;
          _get11 = al;
          memcpy(_memory + (_get9 + 4), _memory + (_get10 + 4), _get11);
          _get12 = out;
          _get13 = al;
          _get14 = b;
          _get15 = bl;
          memcpy(_memory + ((_get12 + 4) + _get13), _memory + (_get14 + 4), _get15);
          _get16 = out;
          return (struct ReturnValue){ _get16, 195 };
        } else {
          _get17 = al;
          _get18 = bl;
          out = __Porffor_malloc(6 + ((_get17 + _get18) * 2));
          _get19 = out;
          _get20 = al;
          _get21 = bl;
          i32_store(0, 0, _get19, _get20 + _get21);
          i = 0;
          // loop 
          j6:;
            _get22 = i;
            _get23 = al;
            // if 
              if (_get22 < _get23) {
                _get24 = out;
                _get25 = i;
                _get26 = a;
                _get27 = i;
                i32_store16(0, 4, _get24 + (_get25 * 2), i32_load8_u(0, 4, _get26 + _get27));
                _get28 = i;
                i = _get28 + 1;
                goto j6;
              }
            // end
            j7:;
          // end
          _get29 = out;
          _get30 = al;
          _get31 = b;
          _get32 = bl;
          memcpy(_memory + ((_get29 + 4) + (_get30 * 2)), _memory + (_get31 + 4), (_get32 * 2));
          _get33 = out;
          return (struct ReturnValue){ _get33, 67 };
        }
      // end
      j4:;
    } else {
      _get34 = bjjtype;
      // if 
        if (_get34 == 195) {
          _get35 = al;
          _get36 = bl;
          out = __Porffor_malloc(6 + ((_get35 + _get36) * 2));
          _get37 = out;
          _get38 = al;
          _get39 = bl;
          i32_store(0, 0, _get37, _get38 + _get39);
          _get40 = out;
          _get41 = a;
          _get42 = al;
          memcpy(_memory + (_get40 + 4), _memory + (_get41 + 4), (_get42 * 2));
          _get43 = out;
          _get44 = al;
          ptr = _get43 + (_get44 * 2);
          i = 0;
          // loop 
          j9:;
            _get45 = i;
            _get46 = bl;
            // if 
              if (_get45 < _get46) {
                _get47 = ptr;
                _get48 = i;
                _get49 = b;
                _get50 = i;
                i32_store16(0, 4, _get47 + (_get48 * 2), i32_load8_u(0, 4, _get49 + _get50));
                _get51 = i;
                i = _get51 + 1;
                goto j9;
              }
            // end
            j10:;
          // end
          _get52 = out;
          return (struct ReturnValue){ _get52, 67 };
        } else {
          _get53 = al;
          _get54 = bl;
          out = __Porffor_malloc(6 + ((_get53 + _get54) * 2));
          _get55 = out;
          _get56 = al;
          _get57 = bl;
          i32_store(0, 0, _get55, _get56 + _get57);
          _get58 = out;
          _get59 = a;
          _get60 = al;
          memcpy(_memory + (_get58 + 4), _memory + (_get59 + 4), (_get60 * 2));
          _get61 = out;
          _get62 = al;
          _get63 = b;
          _get64 = bl;
          memcpy(_memory + ((_get61 + 4) + (_get62 * 2)), _memory + (_get63 + 4), (_get64 * 2));
          _get65 = out;
          return (struct ReturnValue){ _get65, 67 };
        }
      // end
      j8:;
    }
  // end
  j3:;
  return (struct ReturnValue){ 0, 0 };
}

int main() {
  _memory = calloc(1, _memoryPages * 65536);

  _memory[16]=(u8)4;_memory[20]=(u8)97;_memory[21]=(u8)108;_memory[22]=(u8)102;_memory[23]=(u8)97;
  _memory[26]=(u8)5;_memory[30]=(u8)98;_memory[31]=(u8)114;_memory[32]=(u8)97;_memory[33]=(u8)118;_memory[34]=(u8)111;
  _memory[37]=(u8)7;_memory[41]=(u8)99;_memory[42]=(u8)104;_memory[43]=(u8)97;_memory[44]=(u8)114;_memory[45]=(u8)108;_memory[46]=(u8)105;_memory[47]=(u8)101;
  _memory[50]=(u8)5;_memory[54]=(u8)100;_memory[55]=(u8)101;_memory[56]=(u8)108;_memory[57]=(u8)116;_memory[58]=(u8)97;
  _memory[61]=(u8)4;_memory[65]=(u8)101;_memory[66]=(u8)99;_memory[67]=(u8)104;_memory[68]=(u8)111;

  i32 jjlast_type = 0;

  a = 16;
  ajjtype = 195;
  b = 26;
  bjjtype = 195;
  c = 37;
  cjjtype = 195;
  d = 50;
  djjtype = 195;
  e = 61;
  ejjtype = 195;
  t = __performance_now();
  tjjtype = 1;
  i = 0;
  ijjtype = 1;
  // loop 
  j0:;
    // if 
      if (i < 14000) {
        // block 
          const struct ReturnValue _0 = __Porffor_strcat((u32)(a), 195, (u32)(b), 195);
          jjlast_type = _0.type;
          const struct ReturnValue _1 = __Porffor_strcat(_0.value, 195, (u32)(c), 195);
          jjlast_type = _1.type;
          const struct ReturnValue _2 = __Porffor_strcat(_1.value, 195, (u32)(d), 195);
          jjlast_type = _2.type;
          const struct ReturnValue _3 = __Porffor_strcat(_2.value, 195, (u32)(e), 195);
          jjlast_type = _3.type;
          _ = (f64)(_3.value);
          _jjtype = 195;
          i = i + 1;
          if (!(i < 14000)) {
            goto j1;
          }
          const struct ReturnValue _4 = __Porffor_strcat((u32)(a), 195, (u32)(b), 195);
          jjlast_type = _4.type;
          const struct ReturnValue _5 = __Porffor_strcat(_4.value, 195, (u32)(c), 195);
          jjlast_type = _5.type;
          const struct ReturnValue _6 = __Porffor_strcat(_5.value, 195, (u32)(d), 195);
          jjlast_type = _6.type;
          const struct ReturnValue _7 = __Porffor_strcat(_6.value, 195, (u32)(e), 195);
          jjlast_type = _7.type;
          _ = (f64)(_7.value);
          _jjtype = 195;
          i = i + 1;
          if (!(i < 14000)) {
            goto j1;
          }
          const struct ReturnValue _8 = __Porffor_strcat((u32)(a), 195, (u32)(b), 195);
          jjlast_type = _8.type;
          const struct ReturnValue _9 = __Porffor_strcat(_8.value, 195, (u32)(c), 195);
          jjlast_type = _9.type;
          const struct ReturnValue _10 = __Porffor_strcat(_9.value, 195, (u32)(d), 195);
          jjlast_type = _10.type;
          const struct ReturnValue _11 = __Porffor_strcat(_10.value, 195, (u32)(e), 195);
          jjlast_type = _11.type;
          _ = (f64)(_11.value);
          _jjtype = 195;
          i = i + 1;
          if (!(i < 14000)) {
            goto j1;
          }
          const struct ReturnValue _12 = __Porffor_strcat((u32)(a), 195, (u32)(b), 195);
          jjlast_type = _12.type;
          const struct ReturnValue _13 = __Porffor_strcat(_12.value, 195, (u32)(c), 195);
          jjlast_type = _13.type;
          const struct ReturnValue _14 = __Porffor_strcat(_13.value, 195, (u32)(d), 195);
          jjlast_type = _14.type;
          const struct ReturnValue _15 = __Porffor_strcat(_14.value, 195, (u32)(e), 195);
          jjlast_type = _15.type;
          _ = (f64)(_15.value);
          _jjtype = 195;
        // end
        j2:;
        i = i + 1;
        goto j0;
      }
    // end
    j1:;
  // end
  __porf_import_printChar(27);
  __porf_import_printChar(91);
  __porf_import_printChar(51);
  __porf_import_printChar(51);
  __porf_import_printChar(109);
  __porf_import_print(__performance_now() - t);
  __porf_import_printChar(10);
  __porf_import_printChar(27);
  __porf_import_printChar(91);
  __porf_import_printChar(48);
  __porf_import_printChar(109);
  __porf_import_printChar(10);

  return 0;
}