// generated by porffor 0.61.13
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

const f64 NaN = 0e+0/0e+0;
const f64 Infinity = 1e+0/0e+0;

struct ReturnValue {
  f64 value;
  i32 type;
};

char* _memory; u32 _memoryPages = 1;

i32 i32_load(i32 align, i32 offset, i32 pointer) {
  return *((i32*)(_memory + offset + pointer));
}

i32 i32_load8_u(i32 align, i32 offset, i32 pointer) {
  return *((u8*)(_memory + offset + pointer));
}

i32 i32_load16_u(i32 align, i32 offset, i32 pointer) {
  return *((u16*)(_memory + offset + pointer));
}

void __Porffor_printString(f64 arg, i32 argjjtype);

f64 message = 0;
i32 messagejjtype = 0;

void __Porffor_printString(f64 arg, i32 argjjtype) {
  f64 _get13;
  f64 _get12;
  f64 _get11;
  f64 _get10;
  f64 _get9;
  f64 _get8;
  f64 _get7;
  f64 _get6;
  f64 _get5;
  f64 _get4;
  f64 _get3;
  f64 _get2;
  i32 _get1;
  f64 _get0;
  f64 ptr = 0;
  f64 end = 0;

  _get0 = arg;
  ptr = _get0;
  _get1 = argjjtype;
  // if 
    if ((f64)(_get1) == 195) {
      _get2 = ptr;
      _get3 = arg;
      end = _get2 + (f64)(i32_load(1, 0, (u32)(_get3)));
      // loop 
      j1:;
        _get4 = ptr;
        _get5 = end;
        // if 
          if (_get4 < _get5) {
            _get6 = ptr;
            _get7 = ptr;
            ptr = _get7 + 1;
            putchar((int)((f64)(i32_load8_u(0, 4, (i32)(_get6)))));
            goto j1;
          }
        // end
        j2:;
      // end
    } else {
      _get8 = ptr;
      _get9 = arg;
      end = _get8 + ((f64)(i32_load(1, 0, (u32)(_get9))) * 2);
      // loop 
      j3:;
        _get10 = ptr;
        _get11 = end;
        // if 
          if (_get10 < _get11) {
            _get12 = ptr;
            putchar((int)((f64)(i32_load16_u(0, 4, (i32)(_get12)))));
            _get13 = ptr;
            ptr = _get13 + 2;
            goto j3;
          }
        // end
        j4:;
      // end
    }
  // end
  j0:;
  return;
}

int main() {
  _memory = calloc(1, _memoryPages * 65536);

  _memory[16]=(u8)18;_memory[20]=(u8)104;_memory[21]=(u8)101;_memory[22]=(u8)108;_memory[23]=(u8)108;_memory[24]=(u8)111;_memory[25]=(u8)32;_memory[26]=(u8)102;_memory[27]=(u8)114;_memory[28]=(u8)111;_memory[29]=(u8)109;_memory[30]=(u8)32;_memory[31]=(u8)112;_memory[32]=(u8)111;_memory[33]=(u8)114;_memory[34]=(u8)102;_memory[35]=(u8)102;_memory[36]=(u8)111;_memory[37]=(u8)114;

  message = 16;
  messagejjtype = 195;
  __Porffor_printString(message, 195);
  putchar((int)(10));

  return 0;
}