// generated by porffor 
#include <stdint.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

const f64 NaN = 0e+0/0e+0;
const f64 Infinity = 1e+0/0e+0;

struct ReturnValue {
  f64 value;
  i32 type;
};

char* _memory; u32 _memoryPages = 1;


__attribute__((import_module(""), import_name("b")))
extern f64 __porf_import_dong_dom_getElementById(f64);

__attribute__((import_module(""), import_name("a")))
extern void __porf_import_dong_print(f64);


f64 el = 0;
i32 eljjtype = 0;

int main() {
  _memory = calloc(1, _memoryPages * 65536);

  _memory[16]=(u8)6;_memory[20]=(u8)115;_memory[21]=(u8)116;_memory[22]=(u8)97;_memory[23]=(u8)116;_memory[24]=(u8)117;_memory[25]=(u8)115;
  _memory[28]=(u8)14;_memory[32]=(u8)104;_memory[33]=(u8)101;_memory[34]=(u8)108;_memory[35]=(u8)108;_memory[36]=(u8)111;_memory[37]=(u8)32;_memory[38]=(u8)100;_memory[39]=(u8)111;_memory[40]=(u8)109;_memory[41]=(u8)32;_memory[42]=(u8)116;_memory[43]=(u8)101;_memory[44]=(u8)115;_memory[45]=(u8)116;

  el = __porf_import_dong_dom_getElementById(16);
  eljjtype = 1;
  __porf_import_dong_print(28);

  return 0;
}