// generated by porffor 0.61.13
#include <stdint.h>
#include <math.h>
#include <stdlib.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef int32_t i32;
typedef uint32_t u32;
typedef int64_t i64;
typedef uint64_t u64;
typedef float f32;
typedef double f64;

struct ReturnValue {
  f64 value;
  i32 type;
};

#ifndef __porf_nan
#define __porf_nan (NAN)
#endif
#ifndef __porf_infinity
#define __porf_infinity (INFINITY)
#endif

char* t17_memory; u32 t17_memory_pages = 1;

void t17__porf_init(void) {
  if (t17_memory) return;
  t17_memory = calloc(1, t17_memory_pages * 65536);

}

struct ReturnValue t17_increment(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype);
struct ReturnValue t17_getCount(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype);
static i32 t17__Porffor_object_isObject(i32 arg, i32 argjjtype);

static f64 t17_count = 0;
static i32 t17_countjjtype = 0;

int t17_main() {
  t17__porf_init();

  t17_count = 0;
  t17_countjjtype = 1;

  return 0;
}

struct ReturnValue t17_increment(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype) {
  i32 _get2;
  f64 _get1;
  f64 _get0;
  t17_count = t17_count + 1;
  t17_countjjtype = 1;
  _get0 = jjnewtarget;
  // if 
    if (((u32)(_get0)) != 0) {
      _get1 = jjthis;
      _get2 = jjthisjjtype;
      return (struct ReturnValue){ _get1, _get2 };
    }
  // end
  j0:;
  return (struct ReturnValue){ 0, 0 };
}

static i32 t17__Porffor_object_isObject(i32 arg, i32 argjjtype) {
  i32 _get4;
  i32 _get3;
  i32 _get2;
  i32 _get1;
  i32 _get0;
  i32 t = 0;

  _get0 = argjjtype;
  t = _get0;
  _get1 = arg;
  _get2 = t;
  _get3 = t;
  _get4 = t;
  return (((_get1 != 0) & (_get2 > 5)) & (_get3 != 67)) & (_get4 != 195);
}

struct ReturnValue t17_getCount(f64 jjnewtarget, i32 jjnewtargetjjtype, f64 jjthis, i32 jjthisjjtype) {
  i32 _get6;
  f64 _get5;
  i32 _get4;
  f64 _get3;
  i32 _get2;
  f64 _get1;
  f64 _get0;
  f64 jjreturn = 0;
  i32 jjreturnjjtype = 0;

  jjreturn = t17_count;
  jjreturnjjtype = t17_countjjtype;
  _get0 = jjnewtarget;
  // if 
    if (((u32)(_get0)) != 0) {
      _get1 = jjreturn;
      _get2 = jjreturnjjtype;
      // if 
        if ((t17__Porffor_object_isObject((i32)(_get1), _get2)) == 0) {
          _get3 = jjthis;
          _get4 = jjthisjjtype;
          return (struct ReturnValue){ _get3, _get4 };
        }
      // end
      j2:;
    }
  // end
  j1:;
  _get5 = jjreturn;
  _get6 = jjreturnjjtype;
  return (struct ReturnValue){ _get5, _get6 };
}

int t17_export_increment(void) {
  t17__porf_init();
  (void)t17_increment(0, 0, 0, 0);
  return 0;
}

int t17_export_getCount(void) {
  t17__porf_init();
  (void)t17_getCount(0, 0, 0, 0);
  return 0;
}

typedef struct {
  f64 t17_count;
  i32 t17_countjjtype;
} t17_state_t;

void t17_state_capture(t17_state_t* out) {
  out->t17_count = t17_count;
  out->t17_countjjtype = t17_countjjtype;
}

void t17_state_apply(const t17_state_t* in) {
  t17_count = in->t17_count;
  t17_countjjtype = in->t17_countjjtype;
}
